### ISSUE TITLE
No module named 'model.base_transformer'

### ISSUE THREAD

**Issue by XiudingCai** [heeeyk/Transformer-DOA-Prediction#1]
Hi, it seems there are some problems with the code as follows
Traceback (most recent call last):
  File "D:\Transformer-DOA-Prediction-main\mainer\main_featurefusion.py", line 11, in <module>
    from model.featurefusion import trainer, params_save
  File "D:\Transformer-DOA-Prediction-main\model\featurefusion\trainer.py", line 6, in <module>
    from model.featurefusion import tranlstm as transformer
  File "D:\Transformer-DOA-Prediction-main\model\featurefusion\tranlstm.py", line 6, in <module>
    from model.base_transformer.transformer_xl.masks import generate_square_subsequent_mask
ModuleNotFoundError: No module named 'model.base_transformer'

**Comment by heeeyk** [comment]
Thanks for the follow up! We checked and found that we were missing uploading some of the code and will update it later.
